version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: pokeapi-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: pokeapi-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  # app:
  #   build: .
  #   container_name: pegaso-api
  #   ports:
  #     - "${API_PORT}:${API_PORT}"
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   env_file:
  #     - ./.env
  #   restart: always
  #   depends_on:
  #     - mongodb

volumes:
  mongo_data: